/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppDeliveryRouteImport } from './routes/_app.delivery'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryRoute = AppDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delivery': typeof AppDeliveryRoute
  '/finance': typeof AppFinanceRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/sales': typeof AppSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delivery': typeof AppDeliveryRoute
  '/finance': typeof AppFinanceRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/sales': typeof AppSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/delivery': typeof AppDeliveryRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/sales': typeof AppSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/delivery' | '/finance' | '/leaderboard' | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/delivery' | '/finance' | '/leaderboard' | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/delivery'
    | '/_app/finance'
    | '/_app/leaderboard'
    | '/_app/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delivery': {
      id: '/_app/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AppDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDeliveryRoute: typeof AppDeliveryRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppSalesRoute: typeof AppSalesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDeliveryRoute: AppDeliveryRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppSalesRoute: AppSalesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
